# Generated by Django 6.1 on 2026-08-19 16:33

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('package', models.CharField(blank=True, max_length=50)),
                ('value', models.CharField(blank=True, max_length=50)),
                ('pin_count', models.IntegerField(blank=True, null=True)),
                ('voltage', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Comma separated. Also does duty as substitutes.', max_length=200)),
                ('qty_owned', models.PositiveIntegerField(default=0, help_text='Total still yours to use: loose plus held by active projects.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_allocated', models.PositiveIntegerField()),
                ('qty_returned', models.PositiveIntegerField(default=0)),
                ('qty_soldered', models.PositiveIntegerField(default=0)),
                ('qty_broken', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='core.part')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.project')),
            ],
            options={
                'ordering': ['part__name'],
                'constraints': [models.UniqueConstraint(fields=('project', 'part'), name='unique_part_per_project'), models.CheckConstraint(condition=models.Q(('qty_allocated__gt', 0)), name='allocated_is_positive'), models.CheckConstraint(condition=models.Q(('qty_allocated__gte', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('qty_returned'), '+', models.F('qty_soldered')), '+', models.F('qty_broken')))), name='accounted_not_over_allocated')],
            },
        ),
    ]
