# Generated by Django 6.1 on 2026-08-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_projectpart_teardown_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='qty_to_buy',
            field=models.PositiveIntegerField(default=0, help_text="Wanted regardless of any project. Shortfall can only exist attached to a build; this is for 'I am running low on these'."),
        ),
    ]
