"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""
import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True") == "True"

ALLOWED_HOSTS = []

RAILWAY_DOMAIN = os.environ.get("RAILWAY_PUBLIC_DOMAIN")

if RAILWAY_DOMAIN:
    ALLOWED_HOSTS.append(RAILWAY_DOMAIN)
    CSRF_TRUSTED_ORIGINS = [f"https://{RAILWAY_DOMAIN}"]

if DEBUG:
    ALLOWED_HOSTS += ["localhost", "127.0.0.1"]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.app_flags',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Dates render in this zone; USE_TZ keeps everything stored as UTC.
# Override with a TIME_ZONE env var if you move.
TIME_ZONE = os.environ.get("TIME_ZONE", "America/New_York")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# In development there is no collectstatic output to serve from, so let
# WhiteNoise fall back to the staticfiles finders instead of warning.
WHITENOISE_AUTOREFRESH = DEBUG
WHITENOISE_USE_FINDERS = DEBUG

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        # The manifest backend maps every file to a hashed name for cache
        # busting, but it refuses to serve anything unless collectstatic has
        # built that manifest first. That is right for production and wrong
        # for local development and tests, where no build step has run.
        "BACKEND": (
            "whitenoise.storage.CompressedStaticFilesStorage"
            if DEBUG
            else "whitenoise.storage.CompressedManifestStaticFilesStorage"
        ),
    },
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
#
# SMTP credentials come from the environment. Set EMAIL_HOST (plus user,
# password and port) in Railway and real mail starts working with no code
# change. Until then everything goes to the console.
#
# EMAIL_CONFIGURED exists so the app can *hide* password reset rather than
# offer it and silently drop the message into a server log nobody reads. A
# feature that looks like it worked but didn't is worse than one that isn't
# offered.

_EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
EMAIL_CONFIGURED = bool(_EMAIL_HOST)

if EMAIL_CONFIGURED:
    MAILERS = {
        "default": {
            "BACKEND": "django.core.mail.backends.smtp.EmailBackend",
            "OPTIONS": {
                "host": _EMAIL_HOST,
                "port": int(os.environ.get("EMAIL_PORT", "587")),
                "username": os.environ.get("EMAIL_HOST_USER", ""),
                "password": os.environ.get("EMAIL_HOST_PASSWORD", ""),
                "use_tls": os.environ.get("EMAIL_USE_TLS", "True") == "True",
                "timeout": 10,
            },
        },
    }
else:
    MAILERS = {
        "default": {"BACKEND": "django.core.mail.backends.console.EmailBackend"},
    }

DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "inventory@localhost")


# Signup
# Leave SIGNUP_CODE unset and anyone with the URL can create an account. Set it
# to any string in the environment and they need that string to sign up.
SIGNUP_CODE = os.environ.get("SIGNUP_CODE", "")


# Auth routing for the built-in login/logout views.
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "part_list"
LOGOUT_REDIRECT_URL = "login"


# Security
# Everything below is production-only: forcing HTTPS locally would just break
# runserver.
if not DEBUG:
    # Railway terminates TLS at its edge and forwards to the container over
    # plain HTTP. Without this header Django believes every request is
    # insecure, and SECURE_SSL_REDIRECT below would redirect forever.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # One hour. Long enough to be worth having, short enough that a mistake
    # ages out the same afternoon instead of pinning browsers to HTTPS for
    # months. Raise it once you're confident.
    SECURE_HSTS_SECONDS = 3600

    # Both of these are deliberate, and both are what `check --deploy` will
    # nag about. Silenced below so a clean checklist run stays meaningful.
    #
    # includeSubDomains: we're on a *.up.railway.app subdomain we don't own the
    # apex of. Asserting an HSTS policy for domains that aren't ours would be
    # wrong, and on a custom domain later it would need re-deciding anyway.
    #
    # preload: a one-way door. Getting onto the browser preload list is easy
    # and getting off it takes months.
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    SILENCED_SYSTEM_CHECKS = ["security.W005", "security.W021"]
